# More details on how to configure the Travis build
# https://docs.travis-ci.com/user/customizing-the-build/

# Speed up build by leveraging travis caches
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Disabling container based infrastructure
sudo: false

#setting language
language: java

jdk:
  - oraclejdk8

branches:
  #Don't build tags
  except:
    - /^v\d/

#Below skips the installation step completely (https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step)
#We need it because otherwise Travis CI injects an awkward './gradlew assemble' step into the CI workflow
#We want to control and decide what Gradle tasks are executed
install:
  - true

script:
  - ./gradlew clean build -PossrhUsername="${ossrhUsername}" -PossrhPassword="${ossrhPassword}"

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
  - ./gradlew uploadArchives
